name: Publish to npm

on:
  pull_request:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check out main branch
        run: |
          git checkout main

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: npm install

      - name: Configure Git user
        run: |
          git config --global user.email "admin@mysolace.in"
          git config --global user.name "Admin"

      - name: Stash uncommitted changes
        run: |
          git stash --include-untracked

      - name: Bump version
        run: |
          npm version patch # Or use 'minor' or 'major' depending on your strategy
          git push origin main --follow-tags
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish to npm
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
